### ISSUE TITLE
Chyba na velkých souborech

### ISSUE THREAD

**Issue by hojdars** [setnicka/ulozto_downloader#16]
Ahoj,

při stahování většího souboru spadne na KeyError: content-length, celý výpis zde:

```
(venv) d:\>python ulozto_downloader.py --parts 14 "https://uloz.to/file/VdEer7yz/spirited-away-2001-dvdrip-tri-audio-eng-jap-fre-ac3-5-1-dxo-avi"
Starting downloading for url 'https://uloz.to/file/VdEer7yz/spirited-away-2001-dvdrip-tri-audio-eng-jap-fre-ac3-5-1-dxo-avi'
Getting info (filename, filesize, ...)
Traceback (most recent call last):
  File "ulozto_downloader.py", line 233, in <module>
    download(args.url, args.parts, args.output)
  File "ulozto_downloader.py", line 149, in download
    total_size = int(head.headers['Content-Length'])
  File "d:\Home\MFF\diplomka\venv\lib\site-packages\requests\structures.py", line 52, in __getitem__
    return self._store[key.lower()][1]
KeyError: 'content-length'
```

Testováno na linku https://uloz.to/file/VdEer7yz/spirited-away-2001-dvdrip-tri-audio-eng-jap-fre-ac3-5-1-dxo-avi na dvou počítačích, Windows a Linux, Pythony 2.7 a 3.6 - čili všude.

**Comment by AshenCZ** [comment]
Pravděpodobně related k #15 , akorát reportuji také a s konkrétním souborem a error hláškou :-)

**Comment by setnicka** [comment]
Vyřešeno jako #15
