### ISSUE TITLE
Chyba při stahování souboru s mezerami/diakritikou

### ISSUE THREAD

**Issue by hojdars** [setnicka/ulozto_downloader#17]
Ahoj,

na tomto souboru: https://uloz.to/file/lEgCd4ADLfCS/chinaski-ja-a-muj-kun-mp4

Testováno na Windows, Python 3.7

Program spadne po zahájení stahování a stahování failne, celý výpis zde:

```
(venv) d:\>python ulozto_downloader.py --parts 14 "https://uloz.to/file/lEgCd4ADLfCS/chinaski-ja-a-muj-kun-mp4"
Starting downloading for url 'https://uloz.to/file/lEgCd4ADLfCS/chinaski-ja-a-muj-kun-mp4'
Getting info (filename, filesize, ...)
'clear' is not recognized as an internal or external command,
operable program or batch file.
File: Chinaski - Já a můj kůň.mp4 | on-line video
URL: https://uloz.to/file/lEgCd4ADLfCS/chinaski-ja-a-muj-kun-mp4
Size: 3.19MB
Parts: 14 x 0.23MB
←[6;0H←[K[Part 1]       Waiting for download to start...←[7;0H←[K[Part 2]       Waiting for download to start...←[8;0H←[K[Part 3]       Waiting for download to start...←[9;0H←[K[Part 4]       Waiting
for download to start...←[10;0H←[K[Part 5]      Waiting for download to start...←[11;0H←[K[Part 6]      Waiting for download to start...←[12;0H←[K[Part 7]      Waiting for download to start...←[13;0H←
[K[Part 8]      Waiting for download to start...←[14;0H←[K[Part 9]      Waiting for download to start...←[15;0H←[K[Part 10]     Waiting for download to start...←[16;0H←[K[Part 11]     Waiting for down
load to start...←[17;0H←[K[Part 12]     Waiting for download to start...←[18;0H←[K[Part 13]     Waiting for download to start...←[19;0H←[K[Part 14]     Waiting for download to start...←[9;0H←[K[Part 4
]       Starting download←[12;0H←[K[Part 7]     Starting download←[8;0H←[K[Part 3]      Starting download←[10;0H←[K[Part 5]     Starting download←[7;0H←[K[Part 2]      Starting download←[13;0H←[K[Part
 8]     Starting download←[6;0H←[K[Part 1]      Starting download←[19;0H←[K[Part 14]    Starting download←[18;0H←[K[Part 13]    Starting downloadProcess Process-4:
Traceback (most recent call last):
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\ulozto_downloader.py", line 86, in download_part
    with open(part['filename'], 'ab') as f:
OSError: [Errno 22] Invalid argument: './Chinaski - Já a můj kůň.mp4 | on-line video.part04of14'
←[17;0H←[K[Part 12]     Starting downloadProcess Process-7:
Traceback (most recent call last):
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\ulozto_downloader.py", line 86, in download_part
    with open(part['filename'], 'ab') as f:
OSError: [Errno 22] Invalid argument: './Chinaski - Já a můj kůň.mp4 | on-line video.part07of14'
←[14;0H←[K[Part 9]      Starting download←[11;0H←[K[Part 6]     Starting download←[16;0H←[K[Part 11]    Starting downloadProcess Process-8:
Traceback (most recent call last):
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
←[15;0H←[K[Part 10]     Starting downloadProcess Process-1:
Process Process-3:
Traceback (most recent call last):
Traceback (most recent call last):
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\ulozto_downloader.py", line 86, in download_part
    with open(part['filename'], 'ab') as f:
OSError: [Errno 22] Invalid argument: './Chinaski - Já a můj kůň.mp4 | on-line video.part03of14'
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\ulozto_downloader.py", line 86, in download_part
    with open(part['filename'], 'ab') as f:
Process Process-2:
Traceback (most recent call last):
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\ulozto_downloader.py", line 86, in download_part
    with open(part['filename'], 'ab') as f:
OSError: [Errno 22] Invalid argument: './Chinaski - Já a můj kůň.mp4 | on-line video.part02of14'
Process Process-5:
Traceback (most recent call last):
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\ulozto_downloader.py", line 86, in download_part
    with open(part['filename'], 'ab') as f:
OSError: [Errno 22] Invalid argument: './Chinaski - Já a můj kůň.mp4 | on-line video.part05of14'
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\ulozto_downloader.py", line 86, in download_part
    with open(part['filename'], 'ab') as f:
OSError: [Errno 22] Invalid argument: './Chinaski - Já a můj kůň.mp4 | on-line video.part01of14'
Process Process-14:
Traceback (most recent call last):
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\ulozto_downloader.py", line 86, in download_part
    with open(part['filename'], 'ab') as f:
OSError: [Errno 22] Invalid argument: './Chinaski - Já a můj kůň.mp4 | on-line video.part14of14'
OSError: [Errno 22] Invalid argument: './Chinaski - Já a můj kůň.mp4 | on-line video.part08of14'
Process Process-13:
Traceback (most recent call last):
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\ulozto_downloader.py", line 86, in download_part
    with open(part['filename'], 'ab') as f:
OSError: [Errno 22] Invalid argument: './Chinaski - Já a můj kůň.mp4 | on-line video.part13of14'
Process Process-12:
Traceback (most recent call last):
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\ulozto_downloader.py", line 86, in download_part
    with open(part['filename'], 'ab') as f:
OSError: [Errno 22] Invalid argument: './Chinaski - Já a můj kůň.mp4 | on-line video.part12of14'
Process Process-11:
Traceback (most recent call last):
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\ulozto_downloader.py", line 86, in download_part
    with open(part['filename'], 'ab') as f:
OSError: [Errno 22] Invalid argument: './Chinaski - Já a můj kůň.mp4 | on-line video.part11of14'
Process Process-9:
Traceback (most recent call last):
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\ulozto_downloader.py", line 86, in download_part
    with open(part['filename'], 'ab') as f:
OSError: [Errno 22] Invalid argument: './Chinaski - Já a můj kůň.mp4 | on-line video.part09of14'
Process Process-6:
Traceback (most recent call last):
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\ulozto_downloader.py", line 86, in download_part
    with open(part['filename'], 'ab') as f:
OSError: [Errno 22] Invalid argument: './Chinaski - Já a můj kůň.mp4 | on-line video.part06of14'
Process Process-10:
Traceback (most recent call last):
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\Develop\Python-352-64\Lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "d:\ulozto_downloader.py", line 86, in download_part
    with open(part['filename'], 'ab') as f:
OSError: [Errno 22] Invalid argument: './Chinaski - Já a můj kůň.mp4 | on-line video.part10of14'
←[21;0HFailure of one or more downloads, exiting
```

**Comment by setnicka** [comment]
Sorry že se k tomu dostávám až teď.

Na Linuxu se soubor stáhne v pohodě, problém je na Windows ve znaku `|` v názvu souboru. Zkusím vymyslet, jak názvy souborů sanitizovat pro operační systém, na kterém to běží, až se zase někdy dostanu k nějakým Windows :)
